# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f4042b52f8780e2f0d1bca9814c7f08d78579b24eca5e919e4525f46060ddb40d860557d919c9a3b3e918cde6d6cbde7129441298b76f5434e6b59312b80287

test:
  secret_key_base: 46df482219384f8a0d680495b59aab1ce9b6c78a3ab4ad7de0c7be96e2bc77187cf1bc3b8b0ae565ab1e75789ed5064d1f6fb38486515cdbc15cfea0e6ef9285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
